[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[101] ; Poste de la CAISSE
type=endpoint
context=supermarche
disallow=all
allow=ulaw,alaw,h264 ; On autorise la vidéo !
auth=101-auth
aors=101

[101-auth]
type=auth
auth_type=password
password=caisse123
username=101

[101]
type=aor
max_contacts=1
