services:
  asterisk:
    image: andrius/asterisk:latest # Image légère et robuste
    container_name: supermarket-voip
    network_mode: "host" # Crucial pour la VoIP (évite les galères de ports UDP/NAT)
    volumes:
      - ./config:/etc/asterisk # Pour garder la config sur Git
      - ./sounds:/var/lib/asterisk/sounds # Tes messages vocaux personnalisés
    restart: always
    environment:
      - STERISK_COMMAND_ARGS=-vvvvvc # Log détaillé pour débugger
  # 2. Le Panneau de Contrôle (Portainer) - Très léger
  portainer:
    image: portainer/portainer-ce:latest
    container_name: devops-control
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/var/lib/portainer
    restart: always

  # 3. L'Inspecteur ARI (AriNG) - Interface Web légère pour l'API
  aring:
    image: hermsi/aring:latest
    container_name: ari-inspector
    ports:
      - "8081:80" # Accessible sur http://localhost:8081
    restart: always

volumes:
  portainer_data:
